### ISSUE TITLE
Wrong number of stars count

### ISSUE THREAD

**Issue by rilysh** [brunobritodev/awesome-github-stats#18]
**Describe the bug**
When I put my username and submit it, it shows 82k+ number of stars count which I haven't in reality.

**To Reproduce**
1. Go to https://awesome-github-stats.azurewebsites.net/
2. Put your username and click on submit
3. See the results

**Expected behavior**
It should specify correct number of stars count.
**Screenshots**
![Screenshot_20220712-182705_Vivaldi Browser](https://user-images.githubusercontent.com/71683721/178496589-f8231299-47fe-4690-b040-bb1c3f0fa6f6.jpg)

**Desktop (please complete the following information):**
- Device: Samsung M01
 - OS: Android 11
 - Browser: Firefox
 - Version: 102.2.0

**Comment by brunobritodev** [comment]
Yours stars is a collection of all projects you have contributed for. Not only your personals stars, which counts too.

Base query to get stars of your contributions:
```graphql
            query userInfo($login: String!) {
                user(login: $login) {
                    contributionsCollection(from: "2022-01-01T00:00:00Z", to: "2023-01-01T00:00:00Z") {
                        totalCommitContributions
                        totalRepositoryContributions
                        restrictedContributionsCount
                        pullRequestContributionsByRepository{
                          contributions{
                            totalCount
                          }
                          repository {
                            nameWithOwner
                            stargazerCount
                          }
                        }
                        commitContributionsByRepository{
                          contributions {
                            totalCount
                          }
                          repository{
                            nameWithOwner
                            stargazerCount
                          }
                        }
                    }
                }
            }
```
