### ISSUE TITLE
Problem with Total Stars Stat

### ISSUE THREAD

**Issue by bylickilabs** [brunobritodev/awesome-github-stats#22]
**Describe the bug**
|Hello, there is a problem with the star values.|
|---|

### Thanks

![Screenshot](https://user-images.githubusercontent.com/109308073/210197745-d617d6e5-5cc5-4aa3-94df-f6737874a36b.jpg)

**Comment by brunobritodev** [comment]
Hi @bylickilabs,

There is a several layers of cache. From server side it takes 10 hours to update your data. And the Stars count it's take your direct stars (your repos) and indirect stars (repo's you contributed for). For more info  read this [issue](https://github.com/brunobritodev/awesome-github-stats/issues/18#issuecomment-1243806223)

**Comment by bylickilabs** [comment]
Ok, Thanks. Try it again...

**Comment by brunobritodev** [comment]
I can't see where is the problem, could you clarify it?
