### ISSUE TITLE
Use github username instead of empty name

### ISSUE THREAD

**Issue by Fasjeit** [brunobritodev/awesome-github-stats#24]
**Is your feature request related to a problem? Please describe.**
Right now if user have no name stats showing empty string in Title.

[![My Awesome Stats](https://awesome-github-stats.azurewebsites.net/user-stats/fasjeit?cardType=level)](https://git.io/awesome-stats-card)

**Describe the solution you'd like**
It will be nice to have new Property (like `Use username`) or just use username if name is empty.

**Comment by brunobritodev** [comment]
Thank you
